version: '3.8'

services:
  app:
    build: .
    container_name: ulmteammgnt-app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge